### PR TITLE
Firefox version

### PR DESCRIPTION
**Pull request by ArnaudWeyts**
Currently doesn't work yet, the add-on gets loaded in, but it doesn't change any emoji. Seems like firefox is gonna need a modified script.

### CODE REVIEW

**Comment by Haroenv** [comment]
I'll merge this once it works and if people ask for support of this, okay?

**Comment by Haroenv** [comment]
I'm pretty sure that pull requests aren't allowed to see `.enc` files, so this is expected

**Comment by Haroenv** [comment]
These things should be done at `deploy`, and not at every build anyway. The `scripts` step is for stuff like linters and actual TDD

**Comment by ArnaudWeyts** [comment]
Just noticed, whoops.

**Pull request closed without merging**
